
DROP TABLE IF EXISTS article;
CREATE TABLE article(
	aid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	uid VARCHAR(128) NOT NULL,
	caid SMALLINT UNSIGNED NOT NULL,
	title VARCHAR(20),
	contents TEXT(20),
	lasttime DATETIME,
	comment SMALLINT UNSIGNED,
	PRIMARY KEY (aid)
);

DROP TABLE IF EXISTS comment;
CREATE TABLE comment(
	cid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	aid SMALLINT UNSIGNED NOT NULL,
	uid VARCHAR(128) NOT NULL,
	contents TEXT,
	lasttime DATETIME,
	comment SMALLINT UNSIGNED,
	indent TINYINT UNSIGNED,
	PRIMARY KEY (cid)
);

DROP TABLE IF EXISTS user;
CREATE TABLE user(
	uid VARCHAR(128) NOT NULL,
	password VARCHAR(256) NOT NULL,
	name VARCHAR(32),
	PRIMARY KEY (uid)
);

DROP TABLE IF EXISTS catagory;
CREATE TABLE category(
	caid SMALLINT UNSIGNED NOT NULL,
	category VARCHAR(64),
	PRIMARY KEY (caid)
);

ALTER TABLE article
ADD FOREIGN KEY (uid) REFERENCES user (uid);

ALTER TABLE comment
ADD FOREIGN KEY (uid) REFERENCES user (uid);

ALTER TABLE comment
ADD FOREIGN KEY (aid) REFERENCES article (aid);

ALTER TABLE article 
ADD FOREIGN KEY (caid) REFERENCES category (caid);

CREATE DATABASE news;

GRANT ALL ON news.* TO 'deplax'@'localhost' WITH GRANT OPTION;
GRANT ALL ON news.* TO 'deplax'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES; 

SELECT user, host, password FROM user;

UPDATE user SET password=password('secret') WHERE user='deplax';

